language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"

install:
  - pip install --upgrade pytest pytest-cov codecov
  - pip install -e .

script:
  - pytest --cov . --cov-fail-under=50
  - packagename

after_success:
  - codecov
